# Generated by Django 3.1.1 on 2020-12-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20201215_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactnotification',
            name='receiver',
            field=models.IntegerField(blank=True),
        ),
    ]
