# Generated by Django 3.1.1 on 2020-12-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20201215_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactnotification',
            name='sender',
            field=models.IntegerField(blank=True),
        ),
    ]
