# Generated by Django 3.1.1 on 2020-12-11 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='description',
            new_name='about',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_hired',
        ),
    ]
